#!/usr/bin/env python3
"""
Seed a fresh Scenario 7 (S7) run for the Ferring Duplicate PR Detection demo.

Creates:
  - 1 activity_run (status=needs_attention)
  - 13 pre-HITL activity_logs (steps 1-6, with interleaved artifacts)
  - 3 PDF artifacts (linked via artifact_id in log metadata)
  - 5 browser_recordings (steps 2, 7, 8, 9, 13)

Post-HITL steps 7-13 are generated by HitlDecisionPanel.jsx on the dashboard
when the user clicks "Merge & Create PO".

Usage:
    python3 seed_s7_run.py                    # Create a brand-new run
    python3 seed_s7_run.py --reset <run_id>   # Reset an existing run to pre-HITL state

Requires: pip install requests
"""

import argparse
import json
import os
import sys
import time
import uuid

try:
    import requests
except ImportError:
    print("ERROR: 'requests' is required. Install with: pip install requests")
    sys.exit(1)

# ─── Config ────────────────────────────────────────────────────────────────────
SUPABASE_URL = "https://csvjcpmxndgaujxlvikw.supabase.co"
SUPABASE_KEY = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
    "eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzdmpjcG14bmRnYXVqeGx2aWt3"
    "Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjAyOTkzNiwiZXhw"
    "IjoyMDg3NjA1OTM2fQ.81sjVPgI5QzYLlwz1YwbkCNxK-07Rki98px_JUhK6To"
)
PROCESS_ID = "299fead3-7d7c-460f-af50-3546c8f9f6be"
STORAGE_BASE = f"{SUPABASE_URL}/storage/v1/object/public/artifacts"
TEMPLATE_PATH = "ferring-s7-template"

HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=representation",
}

SEED_DATA_FILE = os.path.join(os.path.dirname(__file__), "s7_seed_data.json")

# ─── Supabase helpers ──────────────────────────────────────────────────────────

def sb_post(table: str, rows):
    url = f"{SUPABASE_URL}/rest/v1/{table}"
    resp = requests.post(url, headers=HEADERS, json=rows)
    if resp.status_code not in (200, 201):
        print(f"  ERROR inserting into {table}: {resp.status_code} {resp.text[:200]}")
        sys.exit(1)
    return resp.json()


def sb_delete(table: str, filters: str):
    url = f"{SUPABASE_URL}/rest/v1/{table}?{filters}"
    resp = requests.delete(url, headers=HEADERS)
    if resp.status_code not in (200, 204):
        print(f"  ERROR deleting from {table}: {resp.status_code} {resp.text[:200]}")
        sys.exit(1)


def sb_patch(table: str, filters: str, data: dict):
    url = f"{SUPABASE_URL}/rest/v1/{table}?{filters}"
    resp = requests.patch(url, headers=HEADERS, json=data)
    if resp.status_code not in (200, 204):
        print(f"  ERROR patching {table}: {resp.status_code} {resp.text[:200]}")
        sys.exit(1)
    return resp.json() if resp.text else []


def template_url(filename: str) -> str:
    return f"{STORAGE_BASE}/{TEMPLATE_PATH}/{filename}"


# ─── Core logic ────────────────────────────────────────────────────────────────

def load_seed_data() -> dict:
    with open(SEED_DATA_FILE, "r") as f:
        return json.load(f)


def create_run(seed: dict) -> str:
    """Create a new activity_run and return its ID."""
    run_id = str(uuid.uuid4())
    run_data = seed["run"].copy()
    run_data["id"] = run_id
    result = sb_post("activity_runs", run_data)
    print(f"  Created run: {run_id}")
    return run_id


def reset_run(run_id: str):
    """Reset an existing run to pre-HITL state."""
    print(f"  Deleting post-HITL logs (steps >= 7)...")
    sb_delete("activity_logs", f"run_id=eq.{run_id}&step_number=gte.7")

    print(f"  Resetting run status to needs_attention...")
    sb_patch("activity_runs", f"id=eq.{run_id}", {
        "status": "needs_attention",
        "current_status_text": "Human-in-the-loop decision required — select how to proceed with duplicate PR",
    })
    print(f"  Run {run_id} reset successfully.")

def create_artifacts(run_id: str, seed: dict) -> dict:
    """Create artifact rows and return a map of key -> artifact_id."""
    artifact_ids = {}
    rows = []
    for art in seed["artifacts"]:
        aid = str(uuid.uuid4())
        artifact_ids[art["key"]] = aid
        rows.append({
            "id": aid,
            "run_id": run_id,
            "filename": art["filename"],
            "file_type": art["file_type"],
            "content": art.get("content", ""),
            "url": template_url(art["url_file"]),
        })
    sb_post("artifacts", rows)
    for key, aid in artifact_ids.items():
        print(f"  Artifact [{key}]: {aid}")
    return artifact_ids


def create_logs(run_id: str, seed: dict, artifact_ids: dict):
    """Create the 13 pre-HITL activity_logs with proper artifact links."""
    artifact_links = seed.get("artifact_links", {})
    # Build reverse map: log_index -> (artifact_key, artifact_id)
    index_to_artifact = {}
    for key, link in artifact_links.items():
        idx = link["log_index"]
        index_to_artifact[idx] = artifact_ids[key]

    rows = []
    for i, log in enumerate(seed["logs"]):
        meta = log["metadata"].copy()

        # Inject artifact_id if this log needs one
        if "_needs_artifact" in meta:
            del meta["_needs_artifact"]
            if i in index_to_artifact:
                meta["artifact_id"] = index_to_artifact[i]

        # Update file_url in metadata to use template URLs
        if "file_url" in meta:
            fname = meta.get("file_name", "")
            if fname:
                meta["file_url"] = template_url(fname)

        rows.append({
            "run_id": run_id,
            "step_number": log["step_number"],
            "log_type": log["log_type"],
            "message": log["message"],
            "metadata": meta,
        })

    sb_post("activity_logs", rows)
    print(f"  Created {len(rows)} activity logs (steps 1-6)")


def create_recordings(run_id: str, seed: dict):
    """Create browser_recording rows for video pills."""
    rows = []
    for rec in seed["recordings"]:
        rows.append({
            "run_id": run_id,
            "step_number": rec["step_number"],
            "session_id": f"s7-seed-{run_id[:8]}",
            "s3_url": template_url(rec["file"]),
            "status": "available",
            "metadata": {"label": rec["label"]},
        })
    sb_post("browser_recordings", rows)
    print(f"  Created {len(rows)} browser recordings (steps 2, 7, 8, 9, 13)")

# ─── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Seed or reset an S7 demo run")
    parser.add_argument("--reset", metavar="RUN_ID",
                        help="Reset an existing run to pre-HITL state instead of creating a new one")
    args = parser.parse_args()

    seed = load_seed_data()

    if args.reset:
        run_id = args.reset
        print(f"\n{'='*60}")
        print(f"  RESETTING S7 RUN: {run_id}")
        print(f"{'='*60}\n")
        reset_run(run_id)
    else:
        print(f"\n{'='*60}")
        print(f"  CREATING NEW S7 RUN")
        print(f"{'='*60}\n")

        print("[1/4] Creating activity_run...")
        run_id = create_run(seed)

        print("[2/4] Creating PDF artifacts...")
        artifact_ids = create_artifacts(run_id, seed)

        print("[3/4] Creating pre-HITL logs (steps 1-6)...")
        create_logs(run_id, seed, artifact_ids)

        print("[4/4] Creating browser recordings...")
        create_recordings(run_id, seed)

    dashboard_url = f"https://pace-live-dashboard.vercel.app/run/{run_id}"
    print(f"\n{'='*60}")
    print(f"  DONE!")
    print(f"  Run ID:    {run_id}")
    print(f"  Dashboard: {dashboard_url}")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
